create table "public"."author_crm" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "institution" text,
    "note" text,
    "state" text
);


alter table "public"."author_crm" enable row level security;

CREATE UNIQUE INDEX author_crm_pkey ON public.author_crm USING btree (id);

alter table "public"."author_crm" add constraint "author_crm_pkey" PRIMARY KEY using index "author_crm_pkey";

grant delete on table "public"."author_crm" to "anon";

grant insert on table "public"."author_crm" to "anon";

grant references on table "public"."author_crm" to "anon";

grant select on table "public"."author_crm" to "anon";

grant trigger on table "public"."author_crm" to "anon";

grant truncate on table "public"."author_crm" to "anon";

grant update on table "public"."author_crm" to "anon";

grant delete on table "public"."author_crm" to "authenticated";

grant insert on table "public"."author_crm" to "authenticated";

grant references on table "public"."author_crm" to "authenticated";

grant select on table "public"."author_crm" to "authenticated";

grant trigger on table "public"."author_crm" to "authenticated";

grant truncate on table "public"."author_crm" to "authenticated";

grant update on table "public"."author_crm" to "authenticated";

grant delete on table "public"."author_crm" to "service_role";

grant insert on table "public"."author_crm" to "service_role";

grant references on table "public"."author_crm" to "service_role";

grant select on table "public"."author_crm" to "service_role";

grant trigger on table "public"."author_crm" to "service_role";

grant truncate on table "public"."author_crm" to "service_role";

grant update on table "public"."author_crm" to "service_role";


