create table "public"."papers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying,
    "abstract" character varying,
    "openalex_id" character varying,
    "doi" character varying
);


alter table "public"."papers" enable row level security;

CREATE UNIQUE INDEX papers_pkey ON public.papers USING btree (id);

alter table "public"."papers" add constraint "papers_pkey" PRIMARY KEY using index "papers_pkey";

grant delete on table "public"."papers" to "anon";

grant insert on table "public"."papers" to "anon";

grant references on table "public"."papers" to "anon";

grant select on table "public"."papers" to "anon";

grant trigger on table "public"."papers" to "anon";

grant truncate on table "public"."papers" to "anon";

grant update on table "public"."papers" to "anon";

grant delete on table "public"."papers" to "authenticated";

grant insert on table "public"."papers" to "authenticated";

grant references on table "public"."papers" to "authenticated";

grant select on table "public"."papers" to "authenticated";

grant trigger on table "public"."papers" to "authenticated";

grant truncate on table "public"."papers" to "authenticated";

grant update on table "public"."papers" to "authenticated";

grant delete on table "public"."papers" to "service_role";

grant insert on table "public"."papers" to "service_role";

grant references on table "public"."papers" to "service_role";

grant select on table "public"."papers" to "service_role";

grant trigger on table "public"."papers" to "service_role";

grant truncate on table "public"."papers" to "service_role";

grant update on table "public"."papers" to "service_role";


