create table "public"."ranker_models" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "model_name" text not null,
    "model_data" json
);


alter table "public"."ranker_models" enable row level security;

create table "public"."ranking_authors_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "author_ids" text[] not null,
    "positive_author_ids" text[] not null,
    "negative_author_ids" text[] not null,
    "scores" json
);


alter table "public"."ranking_authors_feedback" enable row level security;

create table "public"."ranking_papers_feedback" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "paper_ids" bigint[] not null,
    "positive_paper_ids" bigint[] not null,
    "negative_paper_ids" bigint[] not null,
    "relevancies" json[] not null
);


alter table "public"."ranking_papers_feedback" enable row level security;

create table "public"."summaries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "original_content" text,
    "summary_content" text,
    "content_hash" text,
    "report_id" bigint,
    "chunk_index" bigint
);


alter table "public"."summaries" enable row level security;

CREATE UNIQUE INDEX ranker_models_model_name_key ON public.ranker_models USING btree (model_name);

CREATE UNIQUE INDEX ranker_models_pkey ON public.ranker_models USING btree (id);

CREATE UNIQUE INDEX ranking_authors_feedback_pkey ON public.ranking_authors_feedback USING btree (id);

CREATE UNIQUE INDEX ranking_feedback_pkey ON public.ranking_papers_feedback USING btree (id);

CREATE UNIQUE INDEX summaries_pkey ON public.summaries USING btree (id);

alter table "public"."ranker_models" add constraint "ranker_models_pkey" PRIMARY KEY using index "ranker_models_pkey";

alter table "public"."ranking_authors_feedback" add constraint "ranking_authors_feedback_pkey" PRIMARY KEY using index "ranking_authors_feedback_pkey";

alter table "public"."ranking_papers_feedback" add constraint "ranking_feedback_pkey" PRIMARY KEY using index "ranking_feedback_pkey";

alter table "public"."summaries" add constraint "summaries_pkey" PRIMARY KEY using index "summaries_pkey";

alter table "public"."ranker_models" add constraint "ranker_models_model_name_key" UNIQUE using index "ranker_models_model_name_key";

alter table "public"."summaries" add constraint "summaries_report_id_fkey" FOREIGN KEY (report_id) REFERENCES reports(id) not valid;

alter table "public"."summaries" validate constraint "summaries_report_id_fkey";

grant delete on table "public"."ranker_models" to "anon";

grant insert on table "public"."ranker_models" to "anon";

grant references on table "public"."ranker_models" to "anon";

grant select on table "public"."ranker_models" to "anon";

grant trigger on table "public"."ranker_models" to "anon";

grant truncate on table "public"."ranker_models" to "anon";

grant update on table "public"."ranker_models" to "anon";

grant delete on table "public"."ranker_models" to "authenticated";

grant insert on table "public"."ranker_models" to "authenticated";

grant references on table "public"."ranker_models" to "authenticated";

grant select on table "public"."ranker_models" to "authenticated";

grant trigger on table "public"."ranker_models" to "authenticated";

grant truncate on table "public"."ranker_models" to "authenticated";

grant update on table "public"."ranker_models" to "authenticated";

grant delete on table "public"."ranker_models" to "service_role";

grant insert on table "public"."ranker_models" to "service_role";

grant references on table "public"."ranker_models" to "service_role";

grant select on table "public"."ranker_models" to "service_role";

grant trigger on table "public"."ranker_models" to "service_role";

grant truncate on table "public"."ranker_models" to "service_role";

grant update on table "public"."ranker_models" to "service_role";

grant delete on table "public"."ranking_authors_feedback" to "anon";

grant insert on table "public"."ranking_authors_feedback" to "anon";

grant references on table "public"."ranking_authors_feedback" to "anon";

grant select on table "public"."ranking_authors_feedback" to "anon";

grant trigger on table "public"."ranking_authors_feedback" to "anon";

grant truncate on table "public"."ranking_authors_feedback" to "anon";

grant update on table "public"."ranking_authors_feedback" to "anon";

grant delete on table "public"."ranking_authors_feedback" to "authenticated";

grant insert on table "public"."ranking_authors_feedback" to "authenticated";

grant references on table "public"."ranking_authors_feedback" to "authenticated";

grant select on table "public"."ranking_authors_feedback" to "authenticated";

grant trigger on table "public"."ranking_authors_feedback" to "authenticated";

grant truncate on table "public"."ranking_authors_feedback" to "authenticated";

grant update on table "public"."ranking_authors_feedback" to "authenticated";

grant delete on table "public"."ranking_authors_feedback" to "service_role";

grant insert on table "public"."ranking_authors_feedback" to "service_role";

grant references on table "public"."ranking_authors_feedback" to "service_role";

grant select on table "public"."ranking_authors_feedback" to "service_role";

grant trigger on table "public"."ranking_authors_feedback" to "service_role";

grant truncate on table "public"."ranking_authors_feedback" to "service_role";

grant update on table "public"."ranking_authors_feedback" to "service_role";

grant delete on table "public"."ranking_papers_feedback" to "anon";

grant insert on table "public"."ranking_papers_feedback" to "anon";

grant references on table "public"."ranking_papers_feedback" to "anon";

grant select on table "public"."ranking_papers_feedback" to "anon";

grant trigger on table "public"."ranking_papers_feedback" to "anon";

grant truncate on table "public"."ranking_papers_feedback" to "anon";

grant update on table "public"."ranking_papers_feedback" to "anon";

grant delete on table "public"."ranking_papers_feedback" to "authenticated";

grant insert on table "public"."ranking_papers_feedback" to "authenticated";

grant references on table "public"."ranking_papers_feedback" to "authenticated";

grant select on table "public"."ranking_papers_feedback" to "authenticated";

grant trigger on table "public"."ranking_papers_feedback" to "authenticated";

grant truncate on table "public"."ranking_papers_feedback" to "authenticated";

grant update on table "public"."ranking_papers_feedback" to "authenticated";

grant delete on table "public"."ranking_papers_feedback" to "service_role";

grant insert on table "public"."ranking_papers_feedback" to "service_role";

grant references on table "public"."ranking_papers_feedback" to "service_role";

grant select on table "public"."ranking_papers_feedback" to "service_role";

grant trigger on table "public"."ranking_papers_feedback" to "service_role";

grant truncate on table "public"."ranking_papers_feedback" to "service_role";

grant update on table "public"."ranking_papers_feedback" to "service_role";

grant delete on table "public"."summaries" to "anon";

grant insert on table "public"."summaries" to "anon";

grant references on table "public"."summaries" to "anon";

grant select on table "public"."summaries" to "anon";

grant trigger on table "public"."summaries" to "anon";

grant truncate on table "public"."summaries" to "anon";

grant update on table "public"."summaries" to "anon";

grant delete on table "public"."summaries" to "authenticated";

grant insert on table "public"."summaries" to "authenticated";

grant references on table "public"."summaries" to "authenticated";

grant select on table "public"."summaries" to "authenticated";

grant trigger on table "public"."summaries" to "authenticated";

grant truncate on table "public"."summaries" to "authenticated";

grant update on table "public"."summaries" to "authenticated";

grant delete on table "public"."summaries" to "service_role";

grant insert on table "public"."summaries" to "service_role";

grant references on table "public"."summaries" to "service_role";

grant select on table "public"."summaries" to "service_role";

grant trigger on table "public"."summaries" to "service_role";

grant truncate on table "public"."summaries" to "service_role";

grant update on table "public"."summaries" to "service_role";


