create table "public"."authors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "openalex_id" text,
    "display_name" text,
    "orcid" text,
    "h_index" bigint,
    "citations" bigint,
    "institutions" text,
    "author_processed" boolean default false,
    "works_count" bigint
);


alter table "public"."authors" enable row level security;

create table "public"."paper_authors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "paper_id" bigint,
    "author_id" bigint,
    "position" text,
    "is_corresponding" boolean
);


alter table "public"."paper_authors" enable row level security;

create table "public"."saved_cipher_queries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cipher_query" text,
    "name" text,
    "user" text
);


alter table "public"."saved_cipher_queries" enable row level security;

create table "public"."test_reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "content" text,
    "content_hash" text
);


alter table "public"."test_reports" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_email" text not null
);


alter table "public"."users" enable row level security;

alter table "public"."author_crm" add column "user_email" text;

alter table "public"."chats" add column "last_updated" timestamp with time zone default (now() AT TIME ZONE 'utc'::text);

alter table "public"."chats" add column "user_email" text;

alter table "public"."papers" add column "cited_by_count" bigint;

alter table "public"."papers" add column "publication_date" date;

CREATE UNIQUE INDEX authors_openalex_id_key ON public.authors USING btree (openalex_id);

CREATE UNIQUE INDEX authors_pkey ON public.authors USING btree (id);

CREATE INDEX idx_author_openalex_id ON public.authors USING btree (openalex_id);

CREATE INDEX idx_paper_openalex_id ON public.papers USING btree (openalex_id);

CREATE UNIQUE INDEX paper_authors_pkey ON public.paper_authors USING btree (id);

CREATE UNIQUE INDEX saved_cipher_queries_pkey ON public.saved_cipher_queries USING btree (id);

CREATE UNIQUE INDEX test_reports_pkey ON public.test_reports USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX "users_userEmail_key" ON public.users USING btree (user_email);

alter table "public"."authors" add constraint "authors_pkey" PRIMARY KEY using index "authors_pkey";

alter table "public"."paper_authors" add constraint "paper_authors_pkey" PRIMARY KEY using index "paper_authors_pkey";

alter table "public"."saved_cipher_queries" add constraint "saved_cipher_queries_pkey" PRIMARY KEY using index "saved_cipher_queries_pkey";

alter table "public"."test_reports" add constraint "test_reports_pkey" PRIMARY KEY using index "test_reports_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."author_crm" add constraint "author_crm_user_email_fkey" FOREIGN KEY (user_email) REFERENCES users(user_email) not valid;

alter table "public"."author_crm" validate constraint "author_crm_user_email_fkey";

alter table "public"."authors" add constraint "authors_openalex_id_key" UNIQUE using index "authors_openalex_id_key";

alter table "public"."chats" add constraint "chats_user_email_fkey" FOREIGN KEY (user_email) REFERENCES users(user_email) not valid;

alter table "public"."chats" validate constraint "chats_user_email_fkey";

alter table "public"."paper_authors" add constraint "paper_authors_author_id_fkey" FOREIGN KEY (author_id) REFERENCES authors(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."paper_authors" validate constraint "paper_authors_author_id_fkey";

alter table "public"."paper_authors" add constraint "paper_authors_paper_id_fkey" FOREIGN KEY (paper_id) REFERENCES papers(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."paper_authors" validate constraint "paper_authors_paper_id_fkey";

alter table "public"."users" add constraint "users_userEmail_key" UNIQUE using index "users_userEmail_key";

grant delete on table "public"."authors" to "anon";

grant insert on table "public"."authors" to "anon";

grant references on table "public"."authors" to "anon";

grant select on table "public"."authors" to "anon";

grant trigger on table "public"."authors" to "anon";

grant truncate on table "public"."authors" to "anon";

grant update on table "public"."authors" to "anon";

grant delete on table "public"."authors" to "authenticated";

grant insert on table "public"."authors" to "authenticated";

grant references on table "public"."authors" to "authenticated";

grant select on table "public"."authors" to "authenticated";

grant trigger on table "public"."authors" to "authenticated";

grant truncate on table "public"."authors" to "authenticated";

grant update on table "public"."authors" to "authenticated";

grant delete on table "public"."authors" to "service_role";

grant insert on table "public"."authors" to "service_role";

grant references on table "public"."authors" to "service_role";

grant select on table "public"."authors" to "service_role";

grant trigger on table "public"."authors" to "service_role";

grant truncate on table "public"."authors" to "service_role";

grant update on table "public"."authors" to "service_role";

grant delete on table "public"."paper_authors" to "anon";

grant insert on table "public"."paper_authors" to "anon";

grant references on table "public"."paper_authors" to "anon";

grant select on table "public"."paper_authors" to "anon";

grant trigger on table "public"."paper_authors" to "anon";

grant truncate on table "public"."paper_authors" to "anon";

grant update on table "public"."paper_authors" to "anon";

grant delete on table "public"."paper_authors" to "authenticated";

grant insert on table "public"."paper_authors" to "authenticated";

grant references on table "public"."paper_authors" to "authenticated";

grant select on table "public"."paper_authors" to "authenticated";

grant trigger on table "public"."paper_authors" to "authenticated";

grant truncate on table "public"."paper_authors" to "authenticated";

grant update on table "public"."paper_authors" to "authenticated";

grant delete on table "public"."paper_authors" to "service_role";

grant insert on table "public"."paper_authors" to "service_role";

grant references on table "public"."paper_authors" to "service_role";

grant select on table "public"."paper_authors" to "service_role";

grant trigger on table "public"."paper_authors" to "service_role";

grant truncate on table "public"."paper_authors" to "service_role";

grant update on table "public"."paper_authors" to "service_role";

grant delete on table "public"."saved_cipher_queries" to "anon";

grant insert on table "public"."saved_cipher_queries" to "anon";

grant references on table "public"."saved_cipher_queries" to "anon";

grant select on table "public"."saved_cipher_queries" to "anon";

grant trigger on table "public"."saved_cipher_queries" to "anon";

grant truncate on table "public"."saved_cipher_queries" to "anon";

grant update on table "public"."saved_cipher_queries" to "anon";

grant delete on table "public"."saved_cipher_queries" to "authenticated";

grant insert on table "public"."saved_cipher_queries" to "authenticated";

grant references on table "public"."saved_cipher_queries" to "authenticated";

grant select on table "public"."saved_cipher_queries" to "authenticated";

grant trigger on table "public"."saved_cipher_queries" to "authenticated";

grant truncate on table "public"."saved_cipher_queries" to "authenticated";

grant update on table "public"."saved_cipher_queries" to "authenticated";

grant delete on table "public"."saved_cipher_queries" to "service_role";

grant insert on table "public"."saved_cipher_queries" to "service_role";

grant references on table "public"."saved_cipher_queries" to "service_role";

grant select on table "public"."saved_cipher_queries" to "service_role";

grant trigger on table "public"."saved_cipher_queries" to "service_role";

grant truncate on table "public"."saved_cipher_queries" to "service_role";

grant update on table "public"."saved_cipher_queries" to "service_role";

grant delete on table "public"."test_reports" to "anon";

grant insert on table "public"."test_reports" to "anon";

grant references on table "public"."test_reports" to "anon";

grant select on table "public"."test_reports" to "anon";

grant trigger on table "public"."test_reports" to "anon";

grant truncate on table "public"."test_reports" to "anon";

grant update on table "public"."test_reports" to "anon";

grant delete on table "public"."test_reports" to "authenticated";

grant insert on table "public"."test_reports" to "authenticated";

grant references on table "public"."test_reports" to "authenticated";

grant select on table "public"."test_reports" to "authenticated";

grant trigger on table "public"."test_reports" to "authenticated";

grant truncate on table "public"."test_reports" to "authenticated";

grant update on table "public"."test_reports" to "authenticated";

grant delete on table "public"."test_reports" to "service_role";

grant insert on table "public"."test_reports" to "service_role";

grant references on table "public"."test_reports" to "service_role";

grant select on table "public"."test_reports" to "service_role";

grant trigger on table "public"."test_reports" to "service_role";

grant truncate on table "public"."test_reports" to "service_role";

grant update on table "public"."test_reports" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


