create table "public"."process_progress_logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "reference_id" character varying,
    "task_id" bigint not null
);


alter table "public"."process_progress_logs" enable row level security;

alter table "public"."processor_progress" alter column "progress" set default '0'::bigint;

CREATE UNIQUE INDEX process_progress_logs_pkey ON public.process_progress_logs USING btree (id);

alter table "public"."process_progress_logs" add constraint "process_progress_logs_pkey" PRIMARY KEY using index "process_progress_logs_pkey";

alter table "public"."process_progress_logs" add constraint "process_progress_logs_task_id_fkey" FOREIGN KEY (task_id) REFERENCES processor_progress(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."process_progress_logs" validate constraint "process_progress_logs_task_id_fkey";

grant delete on table "public"."process_progress_logs" to "anon";

grant insert on table "public"."process_progress_logs" to "anon";

grant references on table "public"."process_progress_logs" to "anon";

grant select on table "public"."process_progress_logs" to "anon";

grant trigger on table "public"."process_progress_logs" to "anon";

grant truncate on table "public"."process_progress_logs" to "anon";

grant update on table "public"."process_progress_logs" to "anon";

grant delete on table "public"."process_progress_logs" to "authenticated";

grant insert on table "public"."process_progress_logs" to "authenticated";

grant references on table "public"."process_progress_logs" to "authenticated";

grant select on table "public"."process_progress_logs" to "authenticated";

grant trigger on table "public"."process_progress_logs" to "authenticated";

grant truncate on table "public"."process_progress_logs" to "authenticated";

grant update on table "public"."process_progress_logs" to "authenticated";

grant delete on table "public"."process_progress_logs" to "service_role";

grant insert on table "public"."process_progress_logs" to "service_role";

grant references on table "public"."process_progress_logs" to "service_role";

grant select on table "public"."process_progress_logs" to "service_role";

grant trigger on table "public"."process_progress_logs" to "service_role";

grant truncate on table "public"."process_progress_logs" to "service_role";

grant update on table "public"."process_progress_logs" to "service_role";


