create table "public"."openalex_topic_assessments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "topic_id" character varying,
    "is_climate_relevant" boolean,
    "analysis" character varying
);


alter table "public"."openalex_topic_assessments" enable row level security;

CREATE UNIQUE INDEX openalex_topic_assessments_pkey ON public.openalex_topic_assessments USING btree (id);

alter table "public"."openalex_topic_assessments" add constraint "openalex_topic_assessments_pkey" PRIMARY KEY using index "openalex_topic_assessments_pkey";

grant delete on table "public"."openalex_topic_assessments" to "anon";

grant insert on table "public"."openalex_topic_assessments" to "anon";

grant references on table "public"."openalex_topic_assessments" to "anon";

grant select on table "public"."openalex_topic_assessments" to "anon";

grant trigger on table "public"."openalex_topic_assessments" to "anon";

grant truncate on table "public"."openalex_topic_assessments" to "anon";

grant update on table "public"."openalex_topic_assessments" to "anon";

grant delete on table "public"."openalex_topic_assessments" to "authenticated";

grant insert on table "public"."openalex_topic_assessments" to "authenticated";

grant references on table "public"."openalex_topic_assessments" to "authenticated";

grant select on table "public"."openalex_topic_assessments" to "authenticated";

grant trigger on table "public"."openalex_topic_assessments" to "authenticated";

grant truncate on table "public"."openalex_topic_assessments" to "authenticated";

grant update on table "public"."openalex_topic_assessments" to "authenticated";

grant delete on table "public"."openalex_topic_assessments" to "service_role";

grant insert on table "public"."openalex_topic_assessments" to "service_role";

grant references on table "public"."openalex_topic_assessments" to "service_role";

grant select on table "public"."openalex_topic_assessments" to "service_role";

grant trigger on table "public"."openalex_topic_assessments" to "service_role";

grant truncate on table "public"."openalex_topic_assessments" to "service_role";

grant update on table "public"."openalex_topic_assessments" to "service_role";


